theme: jekyll-theme-slate
url: "https://kaavatietomalli.fi" # the base hostname & protocol for your site
home: "https://kaavatietomalli.fi"
plugins:
  - jekyll-sitemap
repository: YM-rakennettu-ymparisto/kaavatietomalli
google_analytics: G-TL17CQFMFK
plugins:
- jekyll-sitemap
- kramdown
default_modelversion: '1.0'


