theme: jekyll-theme-slate
url: "https://ilkkarinne.github.io/ry-tietomallit/" # the base hostname & protocol for your site
home: "https://ilkkarinne.github.io/ry-tietomallit/"
plugins:
  - jekyll-sitemap
repository: ilkkarinne/ry-tietomallit
#google_analytics: G-TL17CQFMFK
plugins:
- jekyll-sitemap
- kramdown


